INSERT INTO EXCHANGE_VALUE(ID,TO_CURRENCY,FROM_CURRENCY,EXCHANGE_VALUE) VALUES(1,'INR','USD',65.50);
INSERT INTO EXCHANGE_VALUE(ID,TO_CURRENCY,FROM_CURRENCY,EXCHANGE_VALUE) VALUES(2,'INR','GB',85.50);
INSERT INTO EXCHANGE_VALUE(ID,TO_CURRENCY,FROM_CURRENCY,EXCHANGE_VALUE) VALUES(3,'INR','AED',16.50);